name: Dockerize and Push Todo Client App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.X' 

      - name: Install dependencies
        run: npm install

      - name: Build Docker Image 
        run: docker build -t thehufaaz/todo-client-side:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images
        run: docker push thehufaaz/todo-client-side:latest